version: '2'
services:
  # mongodb:
  #   image: docker.io/bitnami/mongodb:4.2
  #   volumes:
  #     - 'mongodb_data:/bitnami/mongodb'
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #     - MONGODB_USERNAME=bn_parse
  #     - MONGODB_DATABASE=bitnami_parse
  #     - MONGODB_PASSWORD=bitnami123
  parse:
    image: test1
    ports:
      - '1337:1337'
    volumes:
      - 'parse_data:/bitnami/parse'
    # depends_on:
    #   - mongodb
    environment:
      - PARSE_DATABASE_HOST=database_host
      - PARSE_DATABASE_PORT_NUMBER=27017
      - PARSE_DATABASE_USER=issam
      - PARSE_DATABASE_NAME=parse
      - PARSE_DATABASE_PASSWORD=issam123
volumes:
  # mongodb_data:
  #   driver: local
  parse_data:
    driver: local
